# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'HowMuchTrip' do
pod 'Charts'
pod "Parse"
pod 'CalendarView'
pod 'ParseTwitterUtils'
pod 'ParseFacebookUtils'
end

target 'HowMuchTripTests' do
pod 'Charts'
pod "Parse"
pod 'CalendarView'
pod 'ParseTwitterUtils'
pod 'ParseFacebookUtils'
end
